apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: rag-model
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
