apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-models
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/d/rag-data/models
    type: DirectoryOrCreate
